const translations = {
    en: {
        menuTitle: "Our Menu",
        categories: {
          classicPasta: "Classic Pasta",
          stuffedBeefPasta: "Stuffed Beef Pasta",
          stuffedRicottaPasta: "Stuffed Ricotta Pasta",
          supplements: "Supplements",
          lasagna: "Lasagna",
          starters: "Starters",
          desserts: "Desserts",
          drinks: "Drinks",
        },
        items: {
          pestoVerde: "Pesto Verde",
          arrabiata: "Arrabiata",
          bolognaise: "Bolognese",
          carbonara: "Carbonara",
          cremeChampignonPoulet: "Cream Mushroom Chicken",
          scampiCreme: "Scampi Cream",
          fourCheeses: "4 Cheeses",
          indy: "Indy (Chicken Curry)",
          oggi: "Oggi",
          emmental: "Emmental",
          parmesan: "Parmesan",
          chicken: "Chicken",
          noChicken: "No Chicken",
          scampi: "Scampi",
          lasagna: "Lasagna",
          burrata: "Buffalo Burrata",
          cherryTomatoes: "Cherry Tomatoes with Pesto",
          cheesecake: "Caramel Cheesecake",
          chocolateCake: "Chocolate Fondant",
          tiramisu: "Tiramisu",
          softDrink: "Soft Drink",
        },
      },
    fr: {
      menuTitle: "Notre Menu",
      categories: {
        classicPasta: "Pâtes Classiques",
        stuffedBeefPasta: "Pâtes Farcies Bœuf",
        stuffedRicottaPasta: "Pâtes Farcies Ricota",
        supplements: "Suppléments",
        lasagna: "Lasagne",
        starters: "Entrées",
        desserts: "Dessert",
        drinks: "Softs",
      },
      items: {
        pestoVerde: "Pesto Verde",
        arrabiata: "Arrabiata",
        bolognaise: "Bolognaise",
        carbonara: "Carbonara",
        cremeChampignonPoulet: "Crème champignon poulet",
        scampiCreme: "Scampi Crème",
        fourCheeses: "4 Fromages",
        indy: "Indy (poulet curry)",
        oggi: "Oggi",
        emmental: "Emmental",
        parmesan: "Parmesan",
        chicken: "Poulet",
        noChicken: "Sans poulet",
        scampi: "Scampi",
        lasagna: "Lasagne",
        burrata: "Burrata di Bufala",
        cherryTomatoes: "Tomates cerises au pesto",
        cheesecake: "Cheesecake Caramel",
        chocolateCake: "Moelleux Chocolat",
        tiramisu: "Tiramisu",
        softDrink: "Soft",
      },
    },
    nl: {
      menuTitle: "Ons Menu",
      categories: {
        classicPasta: "Klassieke Pasta",
        stuffedBeefPasta: "Gevulde Pasta Rundvlees",
        stuffedRicottaPasta: "Gevulde Pasta Ricotta",
        supplements: "Supplementen",
        lasagna: "Lasagne",
        starters: "Voorgerechten",
        desserts: "Desserts",
        drinks: "Dranken",
      },
      items: {
        pestoVerde: "Pesto Verde",
        arrabiata: "Arrabiata",
        bolognaise: "Bolognaise",
        carbonara: "Carbonara",
        cremeChampignonPoulet: "Champignonroom Kip",
        scampiCreme: "Scampi Room",
        fourCheeses: "4 Kazen",
        indy: "Indy (kip kerrie)",
        oggi: "Oggi",
        emmental: "Emmental",
        parmesan: "Parmezaan",
        chicken: "Kip",
        noChicken: "Zonder kip",
        scampi: "Scampi",
        lasagna: "Lasagne",
        burrata: "Burrata di Bufala",
        cherryTomatoes: "Kerstomaten met pesto",
        cheesecake: "Cheesecake Karamel",
        chocolateCake: "Chocolade Moelleux",
        tiramisu: "Tiramisu",
        softDrink: "Frisdrank",
      },
    },
  };
  
  export default translations;